const products = [
    'Ashoka Ristha 200ml',
    'Ashoka Ristha 450ml',
    'Ashoka Ristha 720ml',
    'Amruta Ristha 200ml',
    'Amruta Ristha 450 ml',
    'Amruta Ristha 720 ml',
    'Arabinda Sava 200 ml',
    'Arabinda Sava 450 ml',
    'Ashwagandha Ristha 200 ml',
    'Ashwagandha Ristha 450 ml',
    'Ashwagandha Ristha 720 ml',
    'Abhaya Ristha 200 ml',
    'Abhaya Ristha 450 ml',
    'Abhaya Ristha 720 ml',
    'Arjuna Ristha 200 ml',
    'Arjuna Ristha 450 ml',
    'Arjuna Ristha 720 ml',
    'Br.Saribadi Salasa(Saribadya sav) 200 ml',
    'Br.Saribadi Salasa(Saribadya sav) 450 ml',
    'Br.Saribadi Salasa(Saribadya sav) 720 ml',
    'Bala Ristha 200 ml',
    'Bala Ristha 450 ml',
    'Bidanga Ristha 200 ml',
    'Bidanga Ristha 450 ml',
    'Chandana Saba 200 ml',
    'Chandana Saba 450 ml',
    'Chandana Saba 720 ml',
    'Dasamula Ristha 200 ml',
    'Dasamula Ristha 450 ml',
    'Dasamula Ristha 720 ml',
    'Drakhya Ristha 200 ml',
    'Drakhya Ristha 450 ml',
    'Drakhya Ristha 720 ml',
    'Dantya Ristha 200 ml',
    'Dantya Ristha 450 ml',
    'Kutaja Ristha 200 ml',
    'Kutaja Ristha 450 ml',
    'Khadira Ristha 200 ml',
    'Khadira Ristha 450 ml',
    'Kumarya Saba 200 ml',
    'Kumarya Saba 450 ml',
    'Kanaka Saba 200 ml',
    'Kanaka Saba 450 ml',
    'Lodhra Saba 200 ml',
    'Lodhra Saba 450 ml',
    'Lodhra Saba 720 ml',
    'Louha Saba 200 ml',
    'Louha Saba 450 ml',
    'Louha Saba 720 ml',
    'Mustakadya Ristha 200 ml',
    'Mustakadya Ristha 450 ml',
    'Patranga Saba 200 ml',
    'Patranga Saba 450 ml',
    'Punarnaba Saba 200 ml',
    'Punarnaba Saba 450 ml',
    'Saraswata Ristha 200 ml',
    'Saraswata Ristha 450 ml',
    'Triphala Ristha 200 ml',
    'Triphala Ristha 450 ml',
    'Usira Saba 200 ml',
    'Usira Saba 450 ml',
    'Amalaki Khanda 200 gm',
    'Amalaki Khanda 500 gm',
    'Basaba Leha 200 gm',
    'Br.Jirakadi Modak 200 gm',
    'Br.Jirakadi Modak 200 gm(pkt)',
    'Br.Kameswar Modak 100 Tab',
    'Br.Methi Modak 200 gm',
    'Br.Methi Modak 200 gm(pkt)',
    'Br.Mundika Topachini Modak 200 gm',
    'Br.Mundika Topachini Modak 200 gm(pkt)',
    'Br.Satabari Rasayan 100 Pkt',
    'Chawan Prash 1 kg',
    'Chawan Prash 250 gm',
    'Chawan Prash 500 gm',
    'Haridra Khanda 200 gm',
    'Haridra Khanda 200 gm(pkt)',
    'Haritaki Khanda 200 gm',
    'Haritaki Khanda 200 gm(pkt)',
    'Maha Jogaraj Guggula 100 gm(Paste)',
    'Maha Rasona Pinda 200 gm',
    'Maha Rasona Pinda 500 gm',
    'Sasank Kiran Modak 200 gm',
    'Sasank Kiran Modak 200 gm(pkt)',
    'Sou.Sunthi Khanda Modak 200 gm',
    'Sou.Sunthi Khanda Modak 200 gm(pkt)',
    'Abha Guggula  100 Tab',
    'Kaisora Guggula 100 Tab',
    'Kanchanar Guggula 100 Tab',
    'Brahmi oil (Taila) 100 ml',
    'Brahmi oil (Taila) 200 ml',
    'Brahmi oil (Taila) 450 ml',
    'Maha Bhrungaraj Oil (taila) 100 ml',
    'Maha Bhrungaraj Oil (taila) 200 ml',
    'Maha Bhrungaraj Oil (taila) 450 ml',
    'Br.Saindhabadi Oil (Taila) 50 ml',
    'Br.Saindhabadi Oil (Taila) 100 ml',
    'Bisamarichyadi Taila 50 ml',
    'Bisamarichyadi Taila 100 ml',
    'Br.Guduchyadi Taila 50 ml',
    'Br.Guduchyadi Taila 100 ml',
    'Dashamula Taila 50 ml ',
    'Dashamula Taila 100 ml',
    'Himasagar Taila 50 ml',
    'Himasagar Taila 100 ml',
    'Kbj.Prasarani Taila 50 ml',
    'Kbj.Prasarani Taila 100 ml',
    'Mahamasha oil (Taila) 50 ml',
    'Mahamasha oil (Taila) 100 ml',
    'Maha Narayan Taila 50 ml',
    'Maha Narayan Taila 100 ml',
    'Madhyam Narayan Taila 50 ml',
    'Madhyam Narayan Taila 100 ml',
    'Sadabindu Taila 25 ml',
    'Sadabindu Taila 50 ml',
    'Suskamuladi Taila 50 ml',
    'Suskamuladi Taila 100 ml',
    'Amlapitta Kuthara Rasa 8 Tab',
    'Abhra Rasayan 8 Tab',
    'Br.Kasturibhairab Rasa 8 Tab',
    'Basant Kusumakar Rasa 16 Tab',
    'Br.Batagajankush 8 Tab',
    'Br.Batachintamani 8 Tab',
    'Br.Bangeshwar 8 Tab',
    'Jogendra Rasa 8 Tab',
    'Rasaraj Rasa 8 Tab',
    'Subarna Pushpasuga 8 Tab',
    'Maha Laxmibilash Rasa 8 Tab',
    'Kumar Kalyan Rasa 8 Tab',
    'Anadabhairab Rasa 16 Tab',
    'Anadabhairab Rasa 32 Tab',
    'Agnitundi Bati 16 Tab',
    'Agnitundi Bati 32 Tab',
    'Arogyabardhani Bati 16 Tab',
    'Arogyabardhani Bati 32 Tab',
    'Br.Chndrodaya Makardhwaja 16 Tab',
    'Br.Chndrodaya Makardhwaja 32 Tab',
    'Balanada Bati 16 Tab',
    'Balanada Bati 32 Tab',
    'Batagajankus Rasa 16 Tab',
    'Batagajankus Rasa 32 Tab',
    'Br.Labangadi Bati 16 Tab',
    'Br.Labangadi Bati  32 Tab',
    'Bhuktapaka Bati 16 Tab',
    'Bhuktapaka Bati 32 Tab',
    'Bataraj Bati 16 Tab',
    'Bataraj Bati 32 Tab',
    'Banari Bati 16 Tab',
    'Banari Bati 32 Tab',
    'Chandraprabha Bati 16 Tab',
    'Chandraprabha Bati 32 Tab',
    'Chandrodwya Barti 1 pc.',
    'Kankayan Gutika 16 Tab',
    'Kankayan Gutika 32 Tab',
    'Maha Sankha Bati 16 Tab',
    'Maha Sankha Bati 32 Tab',
    'Maha Batabidhwansini 16 Tab',
    'Maha Batabidhwansini 32 Tab',
    'Maha Srungarabhra 16 Tab',
    'Maha Srungarabhra 32 Tab',
    'Laghu Puspasuga 16 Tab',
    'Laghu Puspasuga 32 Tab',
    'Rajahaprabartini Bati 16 Tab',
    'Rajahaprabartini Bati 32 Tab',
    'Swarna Balananda Bati 16 Tab',
    'Swarna Balananda Bati 32 Tab',
    'Br.Bidyadharabhra Rasa 16 Tab',
    'Br.Bidyadharabhra Rasa 32 Tab',
    'Bahumutrantak Rasa  16 Tab',
    'Chandramruta Rasa 16 Tab',
    'Chandramruta Rasa  32 Tab',
    'Garvachintamani Rasa 16 Tab',
    'Garvachintamani Rasa 32 Tab',
    'Kumudakar Rasa 16 Tab',
    'Kumudakar Rasa 32 Tab',
    'Kaphaketu Rasa 16 Tab',
    'Kaphaketu Rasa 32 Tab',
    'Kapha Chintaman Rasa 16 Tab',
    'Kapha Chintaman Rasa 32 Tab',
    'krumimudgar Rasa 16 Tab',
    'krumimudgar Rasa 32 Tab',
    'Kasakuthar Rasa 16 Tab',
    'Kasakuthar Rasa 32 Tab',
    'Mrutyunjaya Rasa  16 Tab',
    'Mrutyunjaya Rasa 32 Tab',
    'Karpura Rasa 8 Tab',
    'Sronitargal Rasa  16 Tab',
    'Sronitargal Rasa 32 Tab',
    'Ramaban Rasa 16 Tab',
    'Ramaban Rasa  32 Tab',
    'Nityananda Rasa 16 Tab',
    'Nityananda Rasa 32 Tab',
    'Naradiya Mahalaxmibilas Rasa 16 Tab',
    'Naradiya Mahalaxmibilas Rasa 32 Tab',
    'Kaminibidravan Rasa 16 Tab',
    'Ichhavedi 8 Tab',
    'Sarvangasundar Rasa(Pradar) 16 Tab',
    'Sarvangasundar Rasa(Pradar) 32 Tab',
    'Abipattikar Churna 50gm(pkt)',
    'Abipattikar Churna 100 gm( pkt)',
    'Abipattikar Churna 200 gm',
    'Abipattikar Churna 500 gm',
    'Baiswanar Churna 100 gm',
    'Baiswanar Churna 100 gm(pkt)',
    'Bhaskar Laban 50 gm(pkt)',
    'Bhaskar Laban 100 gm(pkt)',
    'Chandanadi Churna 50 gm(pkt)',
    'Hingwastak Churna 50 gm',
    'Panchasakara Churna 50 gm(pkt)',
    'Panchasakara Churna 100 gm(pkt)',
    'Gandhak Rasayan 20 gm',
    'Gandhak Rasayan 50 gm(pkt)',
    'Sudarsan Churna 50 gm(pkt)',
    'Sudarsan Churna100 gm(Pkt)',
    'Sudarsan Churna100 gm(Cont.)',
    'Talisyadi Churna 50 gm( pkt)',
    'Talisyadi Churna 100 gm',
    'Triphala Churna 50 gm(pkt)',
    'Triphala Churna 100 gm',
    'Brahmi Ghruta 100 gm',
    'Br.Chhagaladi Ghruta 100 gm',
    'Bidangadi Louha 16 tab',
    'Bidangadi Louha 32 tab',
    'Navayas Louha  16 tab',
    'Navayas Louha 32 tab',
    'Pradarantak Louha 16 tab',
    'Pradarantak Louha 32 tab',
    'Sarvajwarahara Louha 16 tab',
    'Sarvajwarahara Louha 32 tab',
    'Bajrakhyara 20 gm',
    'Dhatri Louha 20 gm',
    'Rasa Manikya 10 gm',
    'Siddha Makardhwaja 06(pkt)',
    'Ashwagandhadi Rasayan 200 gm',
    'Balakalyan Tonic 100 ml',
    'Kalyan Sudha 10 ml',
    'Khyudhasagar Modak 100 gm',
    'Maha Rasnadi Modak 200 gm',
    'Sundari Rasayan 200 gm',
    'Sri Balm 10 gm',
    'Sukhmavedi 6gm',
    'Sukhmavedi 50 gm',
    'Sukhmavedi 100gm',
    'Aswagandha Churna 100gm pkt.',
    'Aswagandha Churna 100 gm cont.',
    'Aswagandha Churna 200 gm ',
    'Aswagandha Churna 500 gm ',
    'Aswagandha Churna 1 kg',
    'Amala churna 100 gm pkt.',
    'Amala churna 100 gm cont.',
    'Arjuna Churna 100 gm pkt.',
    'Arjuna Churna 100 gm cont.',
    'Beal churna 100 gm cont.',
    'Gudamari churna 100 gm Pkt.',
    'Gudamari churna 100 gm cont.',
    'Harida churna 100 gm pkt',
    'Harida churna 100 gm cont.',
    'Jasthimadhu Churna 100 gm pkt.',
    'Jasthimadhu Churna 100 gm cont.',
    'Kalara Churna 100 gm pkt',
    'Kalara Churna 100 gm cont.',
    'Methi Churna 100gm pkt ',
    'Methi Churna100 gm cont.',
    'Neemapatra Churna 100 gm pkt',
    'Neemapatra Churna 100 gm cont.',
    'Sunthi Churna 100 gm pkt.',
    'Sunthi Churna 100 gm cont.',
    'Amavatgajendrasingh Modak 200 gm',
    'Br.Lavangadi Modak 200 gm',
    'Br. Pipali Khanda 200 gm',
    'Byaghri Haritaki 200 gm',
    'Byaghri Haritaki 500 gm',
    'Silajit Rasayana 200 gm',
    'Silajit Rasayana 500 gm',
    'Topachini Rasayan 200 gm',
    'Br.Batagajendrasingh 16 tab.',
    'Br.Batagajendrasingh 32 tab.',
    'Br.Guduchyadi 16 tab.',
    'Br.Guduchyadi 32 tab.',
    'Maha Jogaraja guggula100 tab.',
    'Upadanshakuthar 16 tab.',
    'Upadanshakuthar 32 Tab.',
    'Kumarika Bati 16 tab.',
    'Samiragajakeshari 16 tab.',
    'Sitopaladi Churna 100 gm',
    'Trikatu Churna 100 gm',
    'Jambaba Sava450 ml.',
    'Madhurin 200 gm.',
    'Sarpagandha Rista 450 ml.',
    'Sukharasanjibani Rasayana 200 gm.',
    'Kosthasudhi 6 gm',
    'Kosthasudhi 100 gm',
    'Neem Taila 50 ml',
    'Neem Taila 100 ml',
    
]

export { products }