const products = [
    'Aswagandha Churna (100 gm)',
    'Amala churna (100 gm)',
    'Arjuna Churna (100 gm)',
    'Beal churna (100 gm)',
    'Gudamari churna (100 gm)',
    'Harida churna (100 gm)',
    'JamunbeejaChurna (100 gm)',
    'Jasthimadhu Churna (100 gm)',
    'Kalara Churna (100 gm)',
    'Methi Churna (100 gm)',
    'Neemapatra Churna (100 gm)',
    'Sunthi Churna (100 gm)',
    'Amavatgajendrasingh Modak',
    'Br.Lavangadi Modak',
    'Br. Pipali Khanda',
    'Byaghri Haritaki',
    'Silajit Rasayana',
    'Topachini Rasayana',
    'Br. Batagajendrasingh         ',
    'Br.Guduchyadi Louha',
    'Maha Jogaraja guggula',
    'Upadanshakuthar          ',
    'Kumarika Bati',
    'Samiragajakeshari         ',
    'Sitopaladi Churna',
    'Trikatu Churn',
    'Jsmbaba Sava',
    'Madhurin',
    'Sarpagandha Rista ',
    'Sukharasanjibani Rasayana',
]

export { products }